import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

export const metadata: Metadata = {
  title: 'SunStream Digital',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-poppins',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        {/* {children} */}
        <div className="hidden xl:block">{children}</div>
        <div className="xl:hidden h-screen bg-muted flex items-center justify-center">
          <span className="px-4 sm:px-0">
            Responsive not ready yet 🤧. Continue on your pc
          </span>
        </div>
      </body>
    </html>
  )
}
